<?php

namespace Ecole\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespondantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondantRepository extends EntityRepository
{
}
