correspondant:
    path:     /
    defaults: { _controller: "EcoleAdminBundle:Correspondant:index" }

correspondant_show:
    path:     /{id}/show
    defaults: { _controller: "EcoleAdminBundle:Correspondant:show" }

correspondant_new:
    path:     /new
    defaults: { _controller: "EcoleAdminBundle:Correspondant:new" }

correspondant_create:
    path:     /create
    defaults: { _controller: "EcoleAdminBundle:Correspondant:create" }
    methods:  POST

correspondant_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcoleAdminBundle:Correspondant:edit" }

correspondant_update:
    path:     /{id}/update
    defaults: { _controller: "EcoleAdminBundle:Correspondant:update" }
    methods:  [POST, PUT]

correspondant_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcoleAdminBundle:Correspondant:delete" }
    methods:  [POST, DELETE]
