typepage:
    path:     /
    defaults: { _controller: "EcoleAdminBundle:TypePage:index" }

typepage_show:
    path:     /{id}/show
    defaults: { _controller: "EcoleAdminBundle:TypePage:show" }

typepage_new:
    path:     /new
    defaults: { _controller: "EcoleAdminBundle:TypePage:new" }

typepage_create:
    path:     /create
    defaults: { _controller: "EcoleAdminBundle:TypePage:create" }
    methods:  POST

typepage_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcoleAdminBundle:TypePage:edit" }

typepage_update:
    path:     /{id}/update
    defaults: { _controller: "EcoleAdminBundle:TypePage:update" }
    methods:  [POST, PUT]

typepage_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcoleAdminBundle:TypePage:delete" }
    methods:  [POST, DELETE]
