Ecole\AdminBundle\Entity\Actualite:
    type: entity
    table: null
    repositoryClass: Ecole\AdminBundle\Entity\ActualiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: '100'
        contenu:
            type: text
        timestamp:
            type: bigint
        path:
            type: string
            length: 255
        active:
            type: smallint
    lifecycleCallbacks: {  }
