ecole_primaire:
    resource: "@EcolePrimaireBundle/Resources/config/routing.yml"
    prefix:   /primaire

ecole_college:
    resource: "@EcoleCollegeBundle/Resources/config/routing.yml"
    prefix:   /college

ecole_lycee:
    resource: "@EcoleLyceeBundle/Resources/config/routing.yml"
    prefix:   /lycee

ecole_admin:
    resource: "@EcoleAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ecole_site:
    resource: "@EcoleSiteBundle/Resources/config/routing.yml"
    prefix:   /
