<?php
// auto-generated by sfRoutingConfigHandler
// date: 2015/08/30 09:36:27
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'membre',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
'ajax_search_members' => new sfRoute('membre/ajaxlist', array (
  'module' => 'membre',
  'action' => 'ajaxlist',
), array (
), array (
)),
'mailing' => new sfRoute('/mailing', array (
  'module' => 'mailing',
  'action' => 'index',
), array (
), array (
)),
'error_credentials' => new sfRoute('/error/credentials', array (
  'module' => 'error',
  'action' => 'credentials',
), array (
), array (
)),
'setup' => new sfRoute('/install', array (
  'module' => 'install',
  'action' => 'index',
), array (
), array (
)),
);
