<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/30 09:36:27

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'persistent' => true,
  'pooling' => true,
  'dsn' => 'mysql:dbname=u205204631_piwam;host=localhost',
  'username' => 'u205204631_user',
  'password' => 'piwam5',
  'encoding' => 'utf8',
  'name' => 'propel',
)),);
