<?php
// auto-generated by sfViewConfigHandler
// date: 2015/08/30 09:41:59
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Piwam', false, false);
  $response->addMeta('description', 'Gestionnaire d&#039;association', false, false);
  $response->addMeta('language', 'fr', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('pagination.css', '', array ());
  $response->addStylesheet('form.css', '', array ());
  $response->addStylesheet('jquery-ui-1.7.1/smoothness/jquery-ui-1.7.1.custom.css', '', array ());
  $response->addJavascript('scriptaculous/lib/prototype.js', '', array ());
  $response->addJavascript('scriptaculous/src/effects.js', '', array ());
  $response->addJavascript('tiny_mce/tiny_mce.js', '', array ());
  $response->addJavascript('jquery-ui-1.7.1/js/jquery-1.3.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.7.1/js/jquery-ui-1.7.1.custom.min.js', '', array ());
  $response->addJavascript('boxover/boxover.js', '', array ());


