<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:53:50
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_statut',
  ),
  'create' => 
  array (
    'credentials' => 'add_statut',
  ),
  'new' => 
  array (
    'credentials' => 'add_statut',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_statut',
  ),
  'delete' => 
  array (
    'credentials' => 'del_statut',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
