<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:36:27
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'checkconfig' => 
  array (
    'is_secure' => false,
  ),
  'configdatabase' => 
  array (
    'is_secure' => false,
  ),
  'end' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
