<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:51:57
$this->security = array (
  'index' => 
  array (
    'credentials' => 'config_cotisations',
  ),
  'create' => 
  array (
    'credentials' => 'config_cotisations',
  ),
  'new' => 
  array (
    'credentials' => 'config_cotisations',
  ),
  'edit' => 
  array (
    'credentials' => 'config_cotisations',
  ),
  'delete' => 
  array (
    'credentials' => 'config_cotisations',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
