<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:41:59
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_activite',
  ),
  'new' => 
  array (
    'credentials' => 'add_activite',
  ),
  'create' => 
  array (
    'credentials' => 'add_activite',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_activite',
  ),
  'delete' => 
  array (
    'credentials' => 'del_activite',
  ),
  'show' => 
  array (
    'credentials' => 'show_activite',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
