<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:51:53
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_cotisation',
  ),
  'create' => 
  array (
    'credentials' => 'add_cotisation',
  ),
  'new' => 
  array (
    'credentials' => 'add_cotisation',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_cotisation',
  ),
  'delete' => 
  array (
    'credentials' => 'del_cotisation',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
