<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:58:36
$this->security = array (
  'index' => 
  array (
    'credentials' => 'list_compte',
  ),
  'create' => 
  array (
    'credentials' => 'add_compte',
  ),
  'new' => 
  array (
    'credentials' => 'add_compte',
  ),
  'edit' => 
  array (
    'credentials' => 'edit_compte',
  ),
  'delete' => 
  array (
    'credentials' => 'del_compte',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
