<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/08/30 09:36:35
$this->security = array (
  'new' => 
  array (
    'is_secure' => false,
  ),
  'create' => 
  array (
    'is_secure' => false,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'forgottenpassword' => 
  array (
    'is_secure' => false,
  ),
  'edit' => 
  array (
    'credentials' => 'edit_association',
  ),
  'mailing' => 
  array (
    'credentials' => 'mailing',
  ),
  'export' => 
  array (
    'credentials' => 'export',
  ),
  'bilan' => 
  array (
    'credentials' => 'bilan',
  ),
  'config' => 
  array (
    'credentials' => 'edit_association',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
