ecole_site_homepage:
    path:     /
    defaults: { _controller: EcoleSiteBundle:Site:index }

ecole_site_preinsc:
    path:     /preinscription
    defaults: { _controller: EcoleSiteBundle:Site:preinscripion }

eleve_create:
    path:     /creer
    defaults: { _controller: "EcoleSiteBundle:Site:create" }
    methods:  POST
    
ecole_site_actualite:
    path:     /actualite
    defaults: { _controller: EcoleSiteBundle:Site:actualite }
    
ecole_site_contact:
    path:     /contact
    defaults: { _controller: EcoleSiteBundle:Site:contact }

ecole_site_presentation:
    path:     /presentation
    defaults: { _controller: EcoleSiteBundle:Site:presentation }

ecole_site_pedagogie:
    path:     /pedagogie
    defaults: { _controller: EcoleSiteBundle:Site:pedagogie }

ecole_pedagogie_surveille:
    path:     /pedagogie/surveille
    defaults: { _controller: EcoleSiteBundle:Site:surveille }
     
ecole_site_actualite:
    path:     /actualite
    defaults: { _controller: EcoleSiteBundle:Site:actualite}

ecole_site_stat:
    path:     /stat
    defaults: { _controller: EcoleSiteBundle:Site:stat}