
# We allow unregistered user to create a new association
new:
  is_secure:    off
  
create:
  is_secure:    off
  
# And also to list current associations
index:
  is_secure:    off

# And of curse to retrieve a password
forgottenpassword:
  is_secure:    off 
   
  
# For the other actions, we have to get the credentials
edit:
  credentials:  edit_association
  
mailing:
  credentials:  mailing
  
export:
  credentials:  export

bilan:
  credentials:  bilan
  
config:
  credentials:	edit_association
 