ecole_admin_actualite:
    resource: "@EcoleAdminBundle/Resources/config/routing/actualite.yml"
    prefix:   /actualite

ecole_admin_homepage:
    path:     /
    defaults: { _controller: EcoleAdminBundle:Admin:index }

ecole_site_actualite:
    path:     /actu
    defaults: { _controller: EcoleSiteBundle:Site:actualite}