ecole_lycee:
    path:     /
    defaults: { _controller: EcoleLyceeBundle:Lycee:index }

ecole_lycee_objectif:
    path:     /objectif
    defaults: { _controller: EcoleLyceeBundle:Lycee:objectif }

ecole_lycee_biblio:
    path:     /biblio
    defaults: { _controller: EcoleLyceeBundle:Lycee:biblio }

ecole_lycee_program:
    path:     /program
    defaults: { _controller: EcoleLyceeBundle:Lycee:program }
    
ecole_lycee_classe:
    path:     /classe
    defaults: { _controller: EcoleLyceeBundle:Lycee:classe }
    
ecole_lycee_video:
    path:     /video
    defaults: { _controller: EcoleLyceeBundle:Lycee:video }